### ISSUE TITLE
Stream a file larger than 2GB

### ISSUE THREAD

**Issue by gdgudmundson** [skazantsev/WebDavClient#27]
How do I set the WebDavClient to allow GetRawFile to stream a file larger than 2GB

**Comment by skazantsev** [comment]
@gdgudmundson it looks like a bug in the library.

Currently, if you download a file using `WebDavClient` it tries to load it fully into memory instead of actually streaming it.

It can be fixed by adding [HttpCompletionOption.ResponseHeadersRead](https://msdn.microsoft.com/en-us/library/system.net.http.httpcompletionoption.aspx) to a request that is made by the underlying `HttpClient` but it requires additional changes to API to make response of `GetRawFile` and `GetProcessedFile` disposable.

I plan to fix it and release a new version of the library soon.

**Comment by gdgudmundson** [comment]
Another thing to consider is the ContentLength property on the WebDavResource class is an integer which only allows for 2GB file. It would need to be a long to support larger files.

I look forward to a new version.

Thanks!

**Comment by skazantsev** [comment]
Yeah, nice catch!

**Comment by skazantsev** [comment]
I have implemented a fix and released a new version to NuGet.

**Comment by tipa** [comment]
Any chance to make this an option in `GetFileParameters` so we can decide what `HttpCompletionOption` to use? In my use-case I am loading the stream into memory anyways and in order to call the `Length` or `Position` properties on the returned Stream from HttpClient, the `HttpCompletionOption` needs to be `ResponseContentRead`
