### ISSUE TITLE
DisplayName is null

### ISSUE THREAD

**Issue by MohMehrnia** [skazantsev/WebDavClient#36]
Hi, I try read file name on webdev and displayname is null??

**Comment by skazantsev** [comment]
It's not clear if this is the issue of the library or the WebDAV server configuration.
What HTTP request are you sending? What HTTP response are you getting?

A good starting point is too use a tool like [Fiddler](https://www.telerik.com/fiddler) to capture HTTP/HTTPS traffic between the application and the WebDAV server and see what kind of response the WebDAV server returns.

If the field is not present in the HTTP response of WebDAV server then it's the expected behavior of the library; otherwise you can send me the WebDAV response and I can investigate if it's a bug in the lib.

To proxy WebDAV calls through Fiddler you need to pass a WebProxy instance to WebDavClient like explained [here](https://benfoster.io/blog/proxying-httpclient-requests-through-fiddler).
